name: First owrkflow
on: workflow_dispatch
jobs:
  first_job:  #not reserved keyword
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo "hello world"
      - name: install neofetch
        run: sudo apt install neofetch
      - name: neofetch
        run: neofetch
      - name: print bye
        run: echo "done -bye"
    
